name: Build
on: [push, pull_request]
env:
  DOTNET_NOLOGO: true # remove after: https://github.com/actions/virtual-environments/pull/957

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build Reason
      run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 2.3.1
        version=$(minver --tag-prefix v)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release
    - name: Start Services
      run: docker-compose up -d && docker-compose up ready
    - name: Run Tests
      run: dotnet test --configuration Release --no-build
